name: Build & Deploy Worker

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install wasm-pack
        run: curl https://rustwasm.github.io/wasm-pack/installer/init.sh -sSf | sh

      - name: Build WASM
        run: wasm-pack build --target web --release --out-dir dist

      - name: Deploy to Cloudflare
        env:
          CF_ACCOUNT_ID: ${{ secrets.CF_ACCOUNT_ID }}
          CF_API_TOKEN: ${{ secrets.CF_API_TOKEN }}
        run: |
          echo '{"main_module":"your_crate.js","compatibility_date":"2025-05-06"}' > metadata.json
          curl -X PUT "https://api.cloudflare.com/client/v4/accounts/$CF_ACCOUNT_ID/workers/scripts/<SCRIPT_NAME>" \
            -H "Authorization: Bearer $CF_API_TOKEN" \
            -F metadata=@metadata.json;type=application/json \
            -F your_crate.js=@dist/your_crate.js;type=application/javascript+module \
            -F your_crate_bg.wasm=@dist/your_crate_bg.wasm;type=application/wasm
