name: Build & Deploy Worker

on:
  push:
    branches: [ main ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      # 1. 检出仓库
      - name: Checkout repository
        uses: actions/checkout@v4

      # 2. 安装 wasm-pack
      - name: Install wasm-pack
        run: |
          curl https://rustwasm.github.io/wasm-pack/installer/init.sh -sSf | sh

      # 3. 构建 WASM（进入 worker/ 目录，输出到 根/dist）
      - name: Build WASM
        working-directory: worker
        run: |
          wasm-pack build --target web --release --out-dir ../dist

      # 4. 准备 metadata.json
      - name: Prepare metadata
        run: |
          cat <<EOF > metadata.json
          {
            "main_module": "your_crate.js",
            "compatibility_date": "2025-05-06"
          }
          EOF

      # 5. 上传到 Cloudflare
      - name: Deploy to Cloudflare
        env:
          CF_ACCOUNT_ID: ${{ secrets.CF_ACCOUNT_ID }}
          CF_API_TOKEN: ${{ secrets.CF_API_TOKEN }}
        run: |
          curl -X PUT "https://api.cloudflare.com/client/v4/accounts/${CF_ACCOUNT_ID}/workers/scripts/<SCRIPT_NAME>" \
            -H "Authorization: Bearer ${CF_API_TOKEN}" \
            -F metadata=@metadata.json;type=application/json \
            -F your_crate.js=@dist/your_crate.js;type=application/javascript+module \
            -F your_crate_bg.wasm=@dist/your_crate_bg.wasm;type=application/wasm
