name: Build & Package Worker

on:
  push:
    branches:
      - main

jobs:
  build-and-package:
    runs-on: ubuntu-latest

    steps:
      # 1. 检出仓库
      - name: Checkout repository
        uses: actions/checkout@v4

      # 2. 安装 wasm-pack
      - name: Install wasm-pack
        run: |
          curl https://rustwasm.github.io/wasm-pack/installer/init.sh -sSf | sh

      # 3. 构建 WASM（进入 worker/ 目录，输出到 根/dist）
      - name: Build WASM
        working-directory: worker
        run: |
          wasm-pack build --target web --release --out-dir ../dist

      # 4. 打包 dist/ 为 ZIP
      - name: Package dist into ZIP
        run: |
          cd dist
          zip -r ../worker-dist.zip .

      # 5. 上传 ZIP 作为 Artifact
      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: worker-dist
          path: worker-dist.zip
